@startuml

package HQ_NET {

    object HQ_R {
        eth0: 'S 192.168.2.51'
        eth1: ''
    }
    object HQ_SRV {
        eth0: ''
        eth1: 'D 192.168.2.102'
    }

}
package BR_NET {
    object BR_R {
        eth0: 'S 192.168.3.51/24'
        eth1: '192.168.4.1/26'
    }
    object BR_SRV {
        eth0: '192.168.4.2/26'
    }
}

object ISP {
        eth0: '192.168.1.1'
        eth1: '192.168.2.1'
        eth2: '192.168.3.1'
    }
object admin_client

object br_ISP_1 {
    set: 'DHCP 192.168.3.0/24'
}

object br_ISP_2 {
    set: 'DHCP 192.168.2.0/24'
}

br_ISP_1 -- ISP 
br_ISP_2 -- ISP

br_ISP_1 -- BR_R
br_ISP_2 -- HQ_R
br_ISP_2 .. HQ_SRV

admin_client --> ISP : OVPN 192.168.59/0

@enduml
